#!/usr/bin/env dash

get_plugins() {
    rg -A1 'use' '../lua/init_plugins.lua' |
        sed -En 's/.*"(.+)".*/\1/p' |
        rev |
        cut -d'/' -f1 |
        rev
}

main() {
    actual="$(mktemp)"
    reference="$(mktemp)"
    get_plugins >"$actual"
    get_plugins | sort >"$reference"
    diff -su --color=always "$actual" "$reference"
    rm "$actual" "$reference"
}

main
