[buildPlans.iosevka]
family = "Iosevka"
spacing = "fixed"
serifs = "sans"
no-cv-ss = true

[buildPlans.iosevka.variants.design]
y = "straight-turn"
lower-delta = "flat-top"
lower-lambda = "straight-turn"
cyrl-capital-u = "straight-turn"
two = "straight-neck"
six = "closed-contour"
seven = "straight-serifed"
nine = "closed-contour"
asterisk = "hex-high"
number-sign = "slanted"
at = "short"
percent = "rings-continuous-slash"

[buildPlans.iosevka.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka.slopes.oblique]
angle = 9.4
shape = "oblique"
menu = "oblique"
css = "oblique"

[collectPlans.iosevka]
from = ["iosevka"]
