[buildPlans.iosevka]
family = "Iosevka"
spacing = "fixed"
serifs = "sans"
no-cv-ss = true

[buildPlans.iosevka.variants.design]
y = "straight-turn"
lower-lambda = "straight-turn"
cyrl-capital-u = "straight-turn"
two = "straight-neck"
six = "closed-contour"
seven = "straight-serifed"
nine = "closed-contour"
asterisk = "hex-high"
number-sign = "slanted"
at = "short"
percent = "rings-continuous-slash"

[buildPlans.iosevka.widths.normal]
shape = 600
menu = 5
css = "normal"

  [buildPlans.iosevka.slopes]
  upright = "normal"
  oblique = "oblique"
