#!/usr/bin/env dash

source_rc() {
    case "$-" in
        *i*)
            if [ -n "$BASH_VERSION" ]; then
                . "${HOME}/.bashrc"
            fi
            ;;
        *)
            exit 1
            ;;
    esac
}

# shellcheck disable=1091,2034
set_env() {
    set -o allexport

    . "${HOME}/.config/shell/variables"

    . "${HOME}/.nix-profile/etc/profile.d/nix.sh"
    . "${XDG_CONFIG_HOME}/fzf/modus-vivendi"

    LS_COLORS="$(vivid generate modus-vivendi)"
    GEM_HOME="$(ruby -e 'puts Gem.user_dir')"

    PATH="${PATH}:${GEM_HOME}/bin"

    set +o allexport
}

start_xserver() {
    if [ -z "$DISPLAY" ] && [ "$XDG_VTNR" -eq 1 ]; then
        exec startx "$XINITRC"
    fi

}

main() {
    source_rc
    which 'nix' || set_env
    start_xserver
} >/dev/null 2>&1

main
