#!/usr/bin/env dash

. "$HOME/.nix-profile/etc/profile.d/nix.sh"

case "$-" in
    *i*)
        if [ -n "$BASH_VERSION" ]; then
            . "$HOME/.bashrc"
        fi
        ;;
    *)
        exit 1
        ;;
esac

if [ -z "$DISPLAY" ] && [ "$XDG_VTNR" -eq 1 ]; then
    LS_COLORS="$(vivid generate modus-vivendi)"
    export LS_COLORS

    GEM_HOME="$(ruby -e 'puts Gem.user_dir')"
    export GEM_HOME

    export PATH="$PATH:$GEM_HOME/bin"

    # shellcheck disable=1091
    . "$XDG_CONFIG_HOME/fzf/modus-vivendi"
    exec startx "$XINITRC" >/dev/null 2>&1
fi
