#!/usr/bin/env dash

# shellcheck disable=1091
{
    . "$XDG_CONFIG_HOME/shell/aliasrc"
    . "$XDG_CONFIG_HOME/fzf/completion"
    . "$XDG_CONFIG_HOME/git/alias"
    . "$XDG_CONFIG_HOME/nnn/quitcd.bash_zsh"
}

GPG_TTY=$(tty)
export GPG_TTY
