#!/usr/bin/env sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        # shellcheck disable=1090
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

dwm_init() {
    status.py &
    exec dwm
}

xmonad_init() {
    xsetroot -cursor_name left_ptr &
    exec xmonad
}

pkill -f 'status.py'
pkill unclutter

hsetroot -solid black &
lxpolkit &
picom --experimental-backends &
setxkbmap -layout us,ara -variant ,qwerty_digits grp:shifts_toggle &
unclutter &
INIT
