#!/usr/bin/env dash

xrdb -merge "$XDG_CONFIG_HOME/X11/Xresources"

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        # shellcheck disable=1090
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

dwm_init() {
    status.py &
    exec dwm
}

xmonad_init() {
    xsetroot -cursor_name left_ptr &
    exec xmonad
}

pkill -f 'status.py'
pkill unclutter

hsetroot -solid black &
lxpolkit &
picom --experimental-backends &
restore_home &
setxkbmap -layout us,ara -variant ,qwerty_digits grp:shifts_toggle &
unclutter &
xss-lock -l -- secure_lock &
dwm_init
