#!/usr/bin/env dash

get_colours() {
    emacsclient -e '(format "%s" modus-themes-vivendi-colors)'
}

substitute() {
    sed -E \
        -e 's/\)+"?/",\n/g' \
        -e 's/[" ]\(+//g' \
        -e 's/-/_/g' \
        -e 's/\. /= "/g'
}

assign() {
    xargs -0 printf 'return {%s}\n'
}

generate_palette() {
    get_colours | substitute | sort | assign | stylua -s -
}

backup_old_palette() {
    [ -e 'palette.lua' ] && mv 'palette.lua' 'palette.lua.bk'
}

diff_new_palette() {
    [ -e 'palette.lua.bk' ] &&
        diff -u --color=always 'palette.lua.bk' 'palette.lua' &&
        rm 'palette.lua.bk' ||
        exit 0
}

main() {
    backup_old_palette
    generate_palette >'palette.lua'
    diff_new_palette
}

main
