#!/usr/bin/env dash

DIR="$HOME/Projects/Configuration"
DIR_MAIN="$DIR/main"
DIR_HOME="$DIR/home"

init_main() {
    cd "$DIR_MAIN" || exit
    git branch --set-upstream-to 'origin'
}

init_next() {
    git worktree add "$DIR_HOME" 'next'
    ln -srf "$DIR_HOME/.git" "$HOME/.git"
}

main() {
    git clone 'git@github.com:mohamed-abdelnour/Configuration.git' "$DIR_MAIN"
    init_main
    init_next
}

main
