#!/usr/bin/env dash

restore() {
    git clean --force .
    git restore .
}

main() {
    git_file="$(realpath "$HOME/.git")"
    cd "$(dirname "$git_file")" &&
        restore ||
        exit
}

main
