#!/usr/bin/env dash

DIR="$HOME/Projects/Configuration"
DIR_MAIN="$DIR/main"
DIR_HOME="$DIR/home"

push() {
    git push --set-upstream origin "$1"
}

init_main() {
    cd "$DIR_MAIN" || exit
    push 'main'
}

init_next() {
    git worktree add "$DIR_HOME" next
    cd "$HOME" || exit
    ln -s "$DIR_HOME/.git" .
    push 'next'
}

main() {
    git clone 'git@github.com:mohamed-abdelnour/Configuration.git' "$DIR_MAIN"
    init_main
    init_next
}

main
