#!/usr/bin/env dash

get_files() {
    fd --strip-cwd-prefix -t f -H | sort | dmenu -i -l 5
}

cd "$HOME" || exit
file="$(get_files)"
if [ -n "$file" ]; then
    mime="$(xdg-mime query filetype "$file")"
    case "$mime" in
        text*)
            alacritty -e nvim "$file"
            ;;
        *)
            xdg-open "$file"
            ;;
    esac
fi
