#!/usr/bin/env sh

export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
--color=fg:#ffffff
--color=bg:#000000
--color=hl:#feacd0
--color=fg+:#ffffff
--color=bg+:#151823
--color=hl+:#00d3d0
--color=info:#d0bc00
--color=border:#1e1e1e
--color=prompt:#feacd0
--color=pointer:#feacd0
--color=marker:#ff8059
--color=spinner:#feacd0
--color=header:#00d3d0
'
