#!/usr/bin/env sh

export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
--color=fg:#abb2bf
--color=bg:#282c34
--color=hl:#5c6370
--color=fg+:#abb2bf
--color=bg+:#2c323c
--color=hl+:#c678dd
--color=info:#e5c07b
--color=border:#3b4048
--color=prompt:#c678dd
--color=pointer:#c678dd
--color=marker:#e06c75
--color=spinner:#c678dd
--color=header:#5c6370
'
