#!/usr/bin/env sh

alias d='GIT_PAGER=delta'
alias ll='exa -Habgln --color=always --group-directories-first -s Name --time-style=long-iso'
alias ne='nix-env -irA nixpkgs.decPkgs'
alias nman='MANPAGER=nmanpager man'
