format = """
$directory\
$git_branch\
$python\
$cmd_duration\
$line_break\
$status\
$character"""

add_newline = false

[directory]
format = '[\[$path\]]($style)[$read_only]($read_only_style) '
read_only = ' [RO]'
truncate_to_repo = false
truncation_length = 1

[git_branch]
format='[\[$branch\]]($style) '

[character]
# λ
success_symbol = '[\$](bold cyan)'
error_symbol = '[\$](bold red)'
vicmd_symbol = '[̻<](bold purple)'

[python]
detect_extensions = []
detect_files = []
format = '[\[$virtualenv\]]($style) '
style = 'bold purple'
