#!/usr/bin/env dash

rsync -ARXahv \
    /etc/X11/xorg.conf.d/ \
    /etc/default/grub \
    /etc/environment \
    /etc/gtk-2.0/gtkrc \
    /etc/gtk-3.0/settings.ini \
    /etc/sysctl.d/ \
    /etc/systemd/logind.conf \
    /etc/systemd/system/getty@tty1.service.d/ \
    /etc/udev/rules.d/ \
    .

pacman -Qeq > installed_packages.txt
