#!/usr/bin/env dash

rsync -ARXahv \
    /etc/X11/xorg.conf.d/ \
    /etc/environment \
    /etc/gtk-2.0/gtkrc \
    /etc/gtk-3.0/settings.ini \
    /etc/systemd/system/getty@tty1.service.d/override.conf \
    .

pacman -Qeq > installed_packages.txt
