#!/usr/bin/env dash

user='mohamed_abdelnour'

backup() {
    rsync "$@" --delete \
        --exclude="/home/$user/.Xauthority" \
        --exclude="/home/$user/.archive" \
        --exclude="/home/$user/.bare" \
        --exclude="/home/$user/.bash_history" \
        --exclude="/home/$user/.builds" \
        --exclude="/home/$user/.cache" \
        --exclude="/home/$user/.config/tmux/plugins" \
        --exclude="/home/$user/.cpan" \
        --exclude="/home/$user/.cpanm" \
        --exclude="/home/$user/.eclipse" \
        --exclude="/home/$user/.icons" \
        --exclude="/home/$user/.java" \
        --exclude="/home/$user/.keychain" \
        --exclude="/home/$user/.local/lib" \
        --exclude="/home/$user/.local/share" \
        --exclude="/home/$user/.mozilla" \
        --exclude="/home/$user/.mupdf.history" \
        --exclude="/home/$user/.nix-channels" \
        --exclude="/home/$user/.nix-defexpr" \
        --exclude="/home/$user/.nix-profile" \
        --exclude="/home/$user/.npm" \
        --exclude="/home/$user/.pylint.d" \
        --exclude="/home/$user/.python_history" \
        --exclude="/home/$user/.ssh" \
        --exclude="/home/$user/.swt" \
        --exclude="/home/$user/.texlive" \
        --exclude="/home/$user/.themes" \
        --exclude="/home/$user/.thumbnails" \
        --exclude="/home/$user/.tooling" \
        --exclude="/home/$user/.tree-sitter" \
        --exclude="/home/$user/.virtualMachines/ISO" \
        --exclude="/home/$user/.virtualMachines/shared" \
        --exclude="/home/$user/.wget-hsts" \
        --exclude="/home/$user/Programming/Languages/Rust" \
        --exclude="/home/$user/Programming/Miscellaneous/HackerRank" \
        --exclude="/home/$user/Projects/AdventOfCode" \
        /etc /home "$destination"
}

destination="/run/media/$user/Backup/"
output="/home/$user/.cache/backup.txt"
if [ -d "$destination" ]; then
    flags='-AXahnv'
    backup "$flags" > "$output"
    bat "$output"
    printf "Write? "
    read -r choice
    case "$choice" in
        y | Y | yes | Yes | YES)
            flags='-AXahv'
            backup "$flags"
            ;;
    esac
    rm "$output"
fi
