#!/usr/bin/env dash

choice="$(printf "active window\nfullscreen\nselection\n" | dmenu -i)"
month="$(date +'%Y-%m')"
destination="$HOME/Pictures/Screenshots/$month/"
[ -d "$destination" ] || mkdir "$destination"
file_path="$destination$(date +'%Y-%m-%d-%H-%M-%S').png"
case "$choice" in
    'active window')
        maim -d 0.5 -q -u -i "$(xdotool getactivewindow)" "$file_path"
        ;;
    'fullscreen')
        maim -d 0.5 -q -u "$file_path"
        ;;
    'selection')
        maim -d 0.5 -q -u -s "$file_path"
        ;;
esac
