#!/usr/bin/env sh

export JAVA_HOME=/usr/lib/jvm/default
export JDTLS_DIR="$HOME/.local/share/jdtls"

export JAR="$JDTLS_DIR/plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar"
export JDTLS_CONFIG="$JDTLS_DIR/config_linux"
export WORKSPACE="$JDTLS_DIR/workspace"

unset JDTLS_DIR
